name: First workflow
on: [push, workflow_dispatch]
jobs:
  lint:
    steps:
      - name: getting code
        starts on: ubuntu-latest
        uses: actions/checkout@v4
      - name: installing dependencies
        run: npm ci
      - name: linting code
        run: npm run lint
  build:
    needs: lint
    steps:
      - name: getting code
        starts on: ubuntu-latest
        uses: actions/checkout@v4
      - name: installing dependencies
        run: npm ci
      - name: building app
        run: npm run build
  test:
    needs: build
    steps:
      - name: getting code
        starts on: ubuntu-latest
        uses: actions/checkout@v4
      - name: installing dependencies
        run: npm ci
      - name: testing app
        run: npm run test
